<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Navigate to url]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="7805" started-at="2015-02-25T16:11:55Z" finished-at="2015-02-25T16:12:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7805" started-at="2015-02-25T16:11:55Z" finished-at="2015-02-25T16:12:03Z">
      <class name="com.mettl.testcase.Testcase_InvalidLogin">
        <test-method status="PASS" signature="intilize()[pri:0, instance:com.mettl.testcase.Testcase_InvalidLogin@cfe790]" name="intilize" is-config="true" duration-ms="8584" started-at="2015-02-25T21:41:47Z" finished-at="2015-02-25T21:41:55Z">
          <reporter-output>
            <line>
              <![CDATA[Navigate to url]]>
            </line>
          </reporter-output>
        </test-method> <!-- intilize -->
        <test-method status="PASS" signature="enterDataInRegistrationFiled()[pri:0, instance:com.mettl.testcase.Testcase_InvalidLogin@cfe790]" name="enterDataInRegistrationFiled" is-config="true" duration-ms="6811" started-at="2015-02-25T21:41:55Z" finished-at="2015-02-25T21:42:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterDataInRegistrationFiled -->
        <test-method status="PASS" signature="verifyEmployeeISAdded()[pri:0, instance:com.mettl.testcase.Testcase_InvalidLogin@cfe790]" name="verifyEmployeeISAdded" duration-ms="809" started-at="2015-02-25T21:42:02Z" finished-at="2015-02-25T21:42:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmployeeISAdded -->
        <test-method status="FAIL" signature="verifyEmployeeTabledisDeleted()[pri:0, instance:com.mettl.testcase.Testcase_InvalidLogin@cfe790]" name="verifyEmployeeTabledisDeleted" duration-ms="172" started-at="2015-02-25T21:42:03Z" finished-at="2015-02-25T21:42:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Employee table is not sisplayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Employee table is not sisplayed expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.mettl.testcase.Testcase_InvalidLogin.verifyEmployeeTabledisDeleted(Testcase_InvalidLogin.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmployeeTabledisDeleted -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.mettl.testcase.Testcase_InvalidLogin@cfe790]" name="closeBrowser" is-config="true" duration-ms="1002" started-at="2015-02-25T21:42:03Z" finished-at="2015-02-25T21:42:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.mettl.testcase.Testcase_InvalidLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
